export const READ_POSTS = "READ_POSTS";
export const OPER_POST_ERR = "OPER_POST_ERR";

export const READ_COMMENTS = "READ_COMMENTS";
export const CREATE_COMMENT = "CREATE_COMMENT";
export const OPER_COMMENT_ERR = "OPER_COMMENT_ERR";

export const READ_CATEGORIES = "READ_CATEGORIES";
export const OPER_CATEGORY_ERR = "OPER_CATEGORY_ERR";

export const READ_TAGS = "READ_TAGS";
export const OPER_TAG_ERR = "OPER_TAG_ERR";
